/**
 * Proconix PDFKit template — single file: Time Sheet Report + Work Report.
 * Visible styling: dark header band, period highlight, zebra summary grid, job cards + accent bar, photo grid (fit).
 */

const fs = require('fs');
const path = require('path');

var UPLOADS_ROOT = path.resolve(path.join(__dirname, '..', '..', 'uploads'));

var C = {
  headerBg: '#0f172a',
  headerSub: '#94a3b8',
  onHeader: '#ffffff',
  title: '#0f172a',
  muted: '#475569',
  subtle: '#64748b',
  periodBand: '#e2e8f0',
  periodBandBorder: '#cbd5e1',
  rowAlt: '#f1f5f9',
  rowBorder: '#e2e8f0',
  cardFill: '#f8fafc',
  cardStroke: '#cbd5e1',
  accentJob: '#2563eb',
  photoSlotFill: '#ffffff',
  photoSlotStroke: '#94a3b8',
};

var MARGIN = 48;
var HEADER_BAND_H = 108;

function escapeText(s) {
  return s == null ? '' : String(s);
}

function pad2(n) {
  var x = Number(n);
  if (isNaN(x)) return '00';
  return x < 10 ? '0' + x : String(x);
}

/** Normalise to dd/mm/yy for PDF period display (accepts yyyy-mm-dd from HTML date inputs). */
function formatOneDateToDMYY(s) {
  if (s == null || s === '') return '';
  s = String(s).trim();
  if (!s) return '';

  var iso = /^(\d{4})-(\d{2})-(\d{2})/.exec(s);
  if (iso) {
    var yy = iso[1].slice(-2);
    return pad2(iso[3]) + '/' + pad2(iso[2]) + '/' + yy;
  }

  var slash = /^(\d{1,2})\/(\d{1,2})\/(\d{2}|\d{4})$/.exec(s);
  if (slash) {
    var d = pad2(slash[1]);
    var mo = pad2(slash[2]);
    var yPart = slash[3];
    var yyOut = yPart.length === 4 ? yPart.slice(-2) : pad2(yPart);
    return d + '/' + mo + '/' + yyOut;
  }

  return s;
}

function formatDateRange(from, to) {
  var f = formatOneDateToDMYY(from || '');
  var t = formatOneDateToDMYY(to || '');
  if (!f && !t) return '—';
  if (f && t && f !== t) return f + ' to ' + t;
  return f || t;
}

function fmtNumber(n) {
  if (n == null || isNaN(Number(n))) return '0';
  var x = Number(n);
  if (Math.abs(x - Math.round(x)) < 1e-9) return String(Math.round(x));
  return (Math.round(x * 100) / 100).toFixed(2).replace(/\.?0+$/, '');
}

function pluralize(val, unit) {
  var n = Number(val);
  if (isNaN(n)) return unit;
  if (Math.abs(n - 1) < 1e-9) return unit.replace(/s$/i, '');
  return unit;
}

function sumTimeByUnit(jobs) {
  var totalDays = 0;
  var totalHours = 0;
  (jobs || []).forEach(function (j) {
    if (!j) return;
    var d = j.duration != null ? Number(j.duration) : j.duration_value != null ? Number(j.duration_value) : NaN;
    if (isNaN(d)) return;
    var u = j.duration_unit != null ? String(j.duration_unit).toLowerCase() : 'hours';
    if (u === 'days') totalDays += d;
    else totalHours += d;
  });
  return { totalDays, totalHours };
}

function dataUrlToBuffer(dataUrl) {
  if (!dataUrl || typeof dataUrl !== 'string') return null;
  var match = /^data:([^;]+);base64,(.*)$/i.exec(dataUrl);
  if (!match) return null;
  return Buffer.from(match[2] || '', 'base64');
}

function uploadUrlToBuffer(fileUrlOrPath) {
  if (!fileUrlOrPath || typeof fileUrlOrPath !== 'string') return null;
  var p = fileUrlOrPath.trim();
  if (!p.startsWith('/uploads/') || p.includes('..')) return null;
  var rel = p.replace(/^\/uploads\//, '');
  var abs = path.resolve(path.join(UPLOADS_ROOT, rel));
  var root = UPLOADS_ROOT;
  if (abs !== root && !abs.startsWith(root + path.sep)) return null;
  try {
    return fs.readFileSync(abs);
  } catch (_) {
    return null;
  }
}

function resolveImageToBuffer(image) {
  if (!image) return null;
  if (typeof image === 'string') {
    if (/^data:image\//i.test(image)) return dataUrlToBuffer(image);
    return uploadUrlToBuffer(image);
  }
  if (typeof image === 'object') {
    return (
      resolveImageToBuffer(image.dataUrl || image.data_url || image.logoDataUrl || image.logo_data_url || image.url || image.path || image.filePath || image.file_path) ||
      null
    );
  }
  return null;
}

function pageSize(doc) {
  var pageW = doc.page && doc.page.width ? doc.page.width : 595.28;
  var pageH = doc.page && doc.page.height ? doc.page.height : 841.89;
  return { pageW, pageH };
}

function drawFooter(doc, pageW, pageH) {
  doc.save();
  doc.fillColor(C.subtle).font('Helvetica').fontSize(8.5);
  doc.text('Generated by Proconix Work Reports', MARGIN, pageH - 26, {
    width: pageW - MARGIN * 2,
    align: 'center',
  });
  doc.fillColor(C.muted).font('Helvetica-Bold').fontSize(8.5);
  doc.text('WEB : proconix.uk', MARGIN, pageH - 12, {
    width: pageW - MARGIN * 2,
    align: 'center',
  });
  doc.restore();
}

function attachFooters(doc) {
  var addOne = function () {
    var sz = pageSize(doc);
    drawFooter(doc, sz.pageW, sz.pageH);
  };
  doc.on('pageAdded', addOne);
  return addOne;
}

function roundRectFilled(doc, x, y, w, h, r, fillHex, strokeHex, lineW) {
  doc.save();
  doc.lineWidth(lineW == null ? 1 : lineW);
  doc.roundedRect(x, y, w, h, r).fillAndStroke(fillHex, strokeHex || fillHex);
  doc.restore();
}

function drawPhotoCell(doc, buffer, x, y, w, h, r) {
  doc.save();
  doc.lineWidth(1.25);
  doc.roundedRect(x, y, w, h, r);
  doc.fill(C.photoSlotFill);
  doc.strokeColor(C.photoSlotStroke);
  doc.stroke();
  doc.restore();
  if (buffer) {
    doc.save();
    doc.roundedRect(x + 1, y + 1, w - 2, h - 2, Math.max(0, r - 1));
    doc.clip();
    try {
      doc.image(buffer, x, y, { fit: [w, h], align: 'center', valign: 'center' });
    } catch (_) {
      /* ignore */
    }
    doc.restore();
  }
  doc.save();
  doc.lineWidth(1.25);
  doc.roundedRect(x, y, w, h, r).stroke(C.photoSlotStroke);
  doc.restore();
}

function drawSummaryGrid(doc, x, y, w, rows) {
  var labelW = w * 0.36;
  var valueW = w - labelW;
  var rowH = 38;
  var outerR = 14;
  var totalH = rowH * rows.length;

  roundRectFilled(doc, x, y, w, totalH, outerR, '#ffffff', C.cardStroke, 1.5);

  var cy = y;
  rows.forEach(function (row, idx) {
    var bg = idx % 2 === 0 ? C.rowAlt : '#ffffff';
    doc.save();
    doc.fillColor(bg);
    doc.rect(x + 1.5, cy, w - 3, rowH).fill();
    doc.restore();

    if (idx > 0) {
      doc.save();
      doc.strokeColor(C.rowBorder).lineWidth(0.75);
      doc.moveTo(x + 10, cy).lineTo(x + w - 10, cy).stroke();
      doc.restore();
    }

    doc.save();
    doc.strokeColor(C.rowBorder).lineWidth(0.5);
    doc.moveTo(x + labelW, cy + 6).lineTo(x + labelW, cy + rowH - 6).stroke();
    doc.restore();

    doc.save();
    doc.fillColor(C.muted).font('Helvetica-Bold').fontSize(11.5);
    doc.text(row.label, x + 18, cy + 12, { width: labelW - 28 });
    doc.fillColor(C.title).font('Helvetica-Bold').fontSize(11.5);
    doc.text(row.value, x + labelW + 16, cy + 12, { width: valueW - 28 });
    doc.restore();

    cy += rowH;
  });

  return y + totalH;
}

/**
 * QA price work: per-job tables (step / details / quantity). Photos are not included here.
 * @param {import('pdfkit')} doc
 * @param {number} startY
 * @param {number} pageW
 * @param {number} pageH
 * @param {number} innerW
 * @param {{ jobHeading: string, jobTotalStr?: string | null, rows: { stepNr: string, jobDetails: string, quantity: string, amountStr: string }[] }[]} tables
 * @returns {number} next Y
 */
function drawPriceWorkTablesBlock(doc, startY, pageW, pageH, innerW, tables) {
  if (!tables || !tables.length) return startY;
  var textY = startY;
  function pageBreakIf(need) {
    if (textY + need > pageH - 56) {
      doc.addPage();
      textY = 56;
    }
  }
  pageBreakIf(60);
  roundRectFilled(doc, MARGIN, textY, innerW, 22, 8, C.rowAlt, C.periodBandBorder, 1);
  doc.save();
  doc.fillColor(C.title).font('Helvetica-Bold').fontSize(13);
  doc.text('QA price work', MARGIN + 12, textY + 5);
  doc.restore();
  textY += 32;

  var colStepW = 34;
  var colAmtW = 56;
  var colQtyW = 72;
  var gap = 8;
  var colDetW = Math.max(80, innerW - colStepW - colQtyW - colAmtW - gap * 3);

  tables.forEach(function (tbl) {
    var heading = escapeText(tbl.jobHeading || 'Job');
    pageBreakIf(26);
    doc.save();
    doc.fillColor(C.title).font('Helvetica-Bold').fontSize(11.5);
    doc.text(heading, MARGIN, textY, { width: innerW });
    doc.restore();
    textY = doc.y + 8;

    var hdrH = 20;
    pageBreakIf(hdrH + 6);
    doc.save();
    doc.fillColor('#e2e8f0');
    doc.rect(MARGIN, textY, innerW, hdrH).fill();
    doc.fillColor(C.muted).font('Helvetica-Bold').fontSize(8.3);
    doc.text('Step no.', MARGIN + 6, textY + 6, { width: colStepW });
    doc.text('Job details', MARGIN + colStepW + gap, textY + 6, { width: colDetW });
    doc.text('Qty', MARGIN + colStepW + colDetW + gap * 2, textY + 6, { width: colQtyW });
    doc.text(
      'Amount',
      MARGIN + colStepW + colDetW + colQtyW + gap * 3,
      textY + 6,
      { width: colAmtW, align: 'right' }
    );
    doc.restore();
    textY += hdrH;

    (tbl.rows || []).forEach(function (r, ri) {
      var step = escapeText(r.stepNr || '—');
      var det = escapeText(r.jobDetails || '—');
      var qty = escapeText(r.quantity || '—');
      var amt = escapeText(r.amountStr || '—');
      var detW = Math.max(40, colDetW - 6);
      var detH = doc.heightOfString(det, { width: detW, lineGap: 1 });
      var qtyH = doc.heightOfString(qty, { width: colQtyW - 6, lineGap: 1 });
      var amtH = doc.heightOfString(amt, { width: colAmtW - 6, lineGap: 1 });
      var rowH = Math.max(24, Math.max(detH, qtyH, amtH) + 12);
      pageBreakIf(rowH + 4);
      var bg = ri % 2 === 0 ? '#ffffff' : '#f8fafc';
      doc.save();
      doc.fillColor(bg);
      doc.rect(MARGIN, textY, innerW, rowH).fill();
      doc.restore();
      doc.save();
      doc.fillColor(C.title).font('Helvetica').fontSize(9.5);
      doc.text(step, MARGIN + 6, textY + 6, { width: colStepW });
      doc.text(det, MARGIN + colStepW + gap, textY + 6, { width: detW });
      doc.text(qty, MARGIN + colStepW + colDetW + gap * 2, textY + 6, { width: colQtyW - 6 });
      doc.text(amt, MARGIN + colStepW + colDetW + colQtyW + gap * 3, textY + 6, {
        width: colAmtW - 6,
        align: 'right',
      });
      doc.restore();
      doc.save();
      doc.strokeColor(C.rowBorder).lineWidth(0.4);
      doc.moveTo(MARGIN, textY + rowH).lineTo(MARGIN + innerW, textY + rowH).stroke();
      doc.restore();
      textY += rowH;
    });

    if (tbl.jobTotalStr && String(tbl.jobTotalStr).trim()) {
      var footH = 22;
      pageBreakIf(footH + 4);
      doc.save();
      doc.fillColor('#e2e8f0');
      doc.rect(MARGIN, textY, innerW, footH).fill();
      doc.fillColor(C.muted).font('Helvetica-Bold').fontSize(8.5);
      doc.text('Calculated subtotal (price work)', MARGIN + 6, textY + 6, {
        width: innerW - colAmtW - gap * 2,
        align: 'right',
      });
      doc.fillColor('#1e40af').font('Helvetica-Bold').fontSize(10.5);
      doc.text(escapeText(String(tbl.jobTotalStr).trim()), MARGIN + colStepW + colDetW + colQtyW + gap * 3, textY + 5, {
        width: colAmtW - 6,
        align: 'right',
      });
      doc.restore();
      textY += footH;
    }

    textY += 14;
  });

  return textY + 4;
}

function buildTotalTimeText(jobs) {
  var t = sumTimeByUnit(jobs);
  if (t.totalDays > 0 && t.totalHours > 0) {
    return (
      fmtNumber(t.totalDays) +
      ' ' +
      pluralize(t.totalDays, 'days') +
      ' and ' +
      fmtNumber(t.totalHours) +
      ' ' +
      pluralize(t.totalHours, 'hours')
    );
  }
  if (t.totalDays > 0) return fmtNumber(t.totalDays) + ' ' + pluralize(t.totalDays, 'days');
  if (t.totalHours > 0) return fmtNumber(t.totalHours) + ' ' + pluralize(t.totalHours, 'hours');
  return '—';
}

function renderTimesheet(doc, opts) {
  var jobs = Array.isArray(opts.jobs) ? opts.jobs : [];
  var workerName = opts.workerName || 'Operative';
  var projectName = opts.projectName || '—';
  var workType = opts.workType || '—';
  var totalBeforeTax = opts.totalBeforeTax != null && !isNaN(Number(opts.totalBeforeTax)) ? Number(opts.totalBeforeTax) : 0;
  var periodRange = opts.periodRange || '—';
  var logoBuf = opts.logoBuf || null;

  var sz = pageSize(doc);
  var pageW = sz.pageW;
  var pageH = sz.pageH;
  var foot = attachFooters(doc);
  doc.addPage();

  doc.save();
  doc.rect(0, 0, pageW, HEADER_BAND_H).fill(C.headerBg);
  doc.restore();

  doc.save();
  doc.fillColor(C.onHeader).font('Helvetica-Bold').fontSize(28);
  doc.text('Time Sheet Report', MARGIN, 36, { width: pageW - MARGIN * 2 - (logoBuf ? 90 : 0) });
  doc.fillColor(C.headerSub).font('Helvetica').fontSize(12);
  doc.text('Generated by Proconix Work Reports', MARGIN, 74);
  doc.restore();

  if (logoBuf) {
    try {
      doc.image(logoBuf, pageW - MARGIN - 68,34, { width: 56, height: 56, fit: [56, 56] });
    } catch (_) {
      /* ignore */
    }
  }

  var y0 = HEADER_BAND_H + 22;
  var bandH = 44;
  roundRectFilled(doc, MARGIN, y0, pageW - MARGIN * 2, bandH, 10, C.periodBand, C.periodBandBorder, 1);
  doc.save();
  doc.fillColor(C.title).font('Helvetica-Bold').fontSize(13);
  doc.text('For period of time:', MARGIN + 16, y0 + 14);
  doc.font('Helvetica-Bold').fontSize(14).fillColor('#1e40af');
  doc.text(periodRange, MARGIN + 198, y0 + 13, { width: pageW - MARGIN * 2 - 220 });
  doc.restore();

  var tableTop = y0 + bandH + 18;
  var tableW = pageW - MARGIN * 2;
  var totalTimeText = buildTotalTimeText(jobs);
  drawSummaryGrid(doc, MARGIN, tableTop, tableW, [
    { label: 'Operative', value: escapeText(workerName) },
    { label: 'Project', value: escapeText(projectName) },
    { label: 'Work type', value: escapeText(workType) },
    { label: 'Total (before tax)', value: '£' + totalBeforeTax.toFixed(2) },
    { label: 'Total time', value: escapeText(totalTimeText) },
  ]);

  doc.addPage();
  doc.save();
  doc.fillColor(C.title).font('Helvetica-Bold').fontSize(20);
  doc.text('Job list', MARGIN, 44);
  doc.moveTo(MARGIN, 68).lineTo(pageW - MARGIN, 68);
  doc.lineWidth(3);
  doc.strokeColor(C.accentJob);
  doc.stroke();
  doc.restore();

  var currentY = 82;
  var availW = pageW - MARGIN * 2;
  var padX = 18;
  var gapX = 12;
  var gapY = 14;
  var cellR = 10;
  var cellW = (availW - gapX) / 2;
  var cellH = 148;
  var jobCardR = 12;

  jobs.forEach(function (job, jobIdx) {
    job = job || {};
    var location = job.location || '—';
    var description = job.description || '—';
    var dur = job.duration != null ? Number(job.duration) : null;
    var unit = job.duration_unit || 'hours';
    var stageRaw = job.stage || 'ongoing';
    var stage = stageRaw === 'complete' ? 'completed' : stageRaw;
    var progressPct = job.progress_pct != null ? job.progress_pct : null;

    var durationText = '—';
    if (dur != null && !isNaN(Number(dur))) {
      if (unit === 'days') durationText = fmtNumber(dur) + ' ' + pluralize(dur, 'days');
      else durationText = fmtNumber(dur) + ' ' + pluralize(dur, 'hours');
    }

    doc.font('Helvetica').fontSize(11.5);
    var descW = availW - padX * 2 - 8;
    var descH = doc.heightOfString(String(description), { width: descW });

    var headerBlock = 30;
    var metaBlock = 38;
    var progBlock = stage === 'ongoing' && progressPct != null && !isNaN(Number(progressPct)) ? 20 : 0;
    var padY = 16;
    var textH = padY + headerBlock + descH + 8 + metaBlock + progBlock + padY;

    if (currentY + textH > pageH - 56) {
      doc.addPage();
      currentY = 72;
    }

    doc.save();
    doc.rect(MARGIN, currentY, 5, textH).fill(C.accentJob);
    doc.restore();
    roundRectFilled(doc, MARGIN + 5, currentY, availW - 5, textH, jobCardR, C.cardFill, C.cardStroke, 1.25);

    var tx = MARGIN + 5 + padX;
    var ty = currentY + padY;
    doc.save();
    doc.fillColor(C.title).font('Helvetica-Bold').fontSize(15);
    doc.text('Job ' + (jobIdx + 1) + ' · ' + location, tx, ty, { width: availW - padX * 2 - 8 });
    ty += 24;
    doc.fillColor(C.muted).font('Helvetica-Bold').fontSize(10);
    doc.text('DESCRIPTION', tx, ty);
    ty += 14;
    doc.fillColor(C.title).font('Helvetica').fontSize(11.5);
    doc.text(String(description), tx, ty, { width: descW });
    ty += descH + 10;

    doc.font('Helvetica-Bold').fontSize(11);
    doc.fillColor('#1e40af');
    doc.text('Time spent: ' + durationText, tx, ty);
    ty += 16;
    doc.fillColor(stage === 'completed' ? '#15803d' : '#b45309');
    doc.text('Job stage: ' + String(stage), tx, ty);
    ty += 16;
    if (progBlock) {
      doc.fillColor(C.title).font('Helvetica-Bold');
      doc.text('Progress: ' + Number(progressPct) + '%', tx, ty);
    }
    doc.restore();

    currentY += textH + 16;

    var photos = Array.isArray(job.photos)
      ? job.photos
      : Array.isArray(job.photoUrls)
        ? job.photoUrls
        : Array.isArray(job.photo_urls)
          ? job.photo_urls
          : [];

    var row = 0;
    var col = 0;
    for (var i = 0; i < photos.length; i++) {
      if (currentY + row * (cellH + gapY) + cellH > pageH - 46) {
        doc.addPage();
        currentY = 72;
        row = 0;
        col = 0;
      }
      var xCell = MARGIN + col * (cellW + gapX);
      var yCell = currentY + row * (cellH + gapY);
      var buf = resolveImageToBuffer(photos[i]);
      drawPhotoCell(doc, buf, xCell, yCell, cellW, cellH, cellR);
      col += 1;
      if (col > 1) {
        col = 0;
        row += 1;
      }
    }
    var photoRows = photos.length ? row + (col > 0 ? 1 : 0) : 0;
    if (photoRows > 0) {
      currentY += photoRows * (cellH + gapY) - gapY;
    }
    currentY += 20;
  });

  foot();
}

function renderWorkReport(doc, opts) {
  var photos = Array.isArray(opts.photos) ? opts.photos : [];

  var workSummary = opts.workSummary || '—';
  var notes = opts.notes || '—';
  var totalBeforeTax = opts.totalBeforeTax != null && !isNaN(Number(opts.totalBeforeTax)) ? Number(opts.totalBeforeTax) : 0;
  var periodRange = opts.periodRange || '—';
  var workerName = opts.workerName || 'Operative';
  var projectName = opts.projectName || '—';
  var location = opts.location || '—';
  var logoBuf = opts.logoBuf || null;

  var sz = pageSize(doc);
  var pageW = sz.pageW;
  var pageH = sz.pageH;
  var foot = attachFooters(doc);
  doc.addPage();

  doc.save();
  doc.rect(0, 0, pageW, HEADER_BAND_H).fill(C.headerBg);
  doc.restore();

  doc.save();
  doc.fillColor(C.onHeader).font('Helvetica-Bold').fontSize(28);
  doc.text('Work Report', MARGIN, 36, { width: pageW - MARGIN * 2 - (logoBuf ? 90 : 0) });
  doc.fillColor(C.headerSub).font('Helvetica').fontSize(12);
  doc.text('Generated by Proconix Work Reports', MARGIN, 74);
  doc.restore();

  if (logoBuf) {
    try {
      doc.image(logoBuf, pageW - MARGIN - 68, 34, { width: 56, height: 56, fit: [56, 56] });
    } catch (_) {
      /* ignore */
    }
  }

  var y0 = HEADER_BAND_H + 22;
  var bandH = 44;
  roundRectFilled(doc, MARGIN, y0, pageW - MARGIN * 2, bandH, 10, C.periodBand, C.periodBandBorder, 1);
  doc.save();
  doc.fillColor(C.title).font('Helvetica-Bold').fontSize(13);
  doc.text('For period of time:', MARGIN + 16, y0 + 14);
  doc.font('Helvetica-Bold').fontSize(14).fillColor('#1e40af');
  doc.text(periodRange, MARGIN + 198, y0 + 13, { width: pageW - MARGIN * 2 - 220 });
  doc.restore();

  var tableTop = y0 + bandH + 18;
  var tableBot = drawSummaryGrid(doc, MARGIN, tableTop, pageW - MARGIN * 2, [
    { label: 'Operative', value: escapeText(workerName) },
    { label: 'Project', value: escapeText(projectName) },
    { label: 'Location', value: escapeText(location) },
    { label: 'Total (before tax)', value: '£' + totalBeforeTax.toFixed(2) },
  ]);

  var textY = tableBot + 26;
  var innerW = pageW - MARGIN * 2;

  roundRectFilled(doc, MARGIN, textY, innerW, 22, 8, C.rowAlt, C.periodBandBorder, 1);
  doc.save();
  doc.fillColor(C.title).font('Helvetica-Bold').fontSize(13);
  doc.text('Work performed', MARGIN + 12, textY + 5);
  doc.restore();
  textY += 32;
  doc.save();
  doc.fillColor(C.title).font('Helvetica').fontSize(11.5);
  doc.text(String(workSummary), MARGIN, textY, { width: innerW });
  doc.restore();
  textY = doc.y + 22;

  roundRectFilled(doc, MARGIN, textY, innerW, 22, 8, C.rowAlt, C.periodBandBorder, 1);
  doc.save();
  doc.fillColor(C.title).font('Helvetica-Bold').fontSize(13);
  doc.text('Notes', MARGIN + 12, textY + 5);
  doc.restore();
  textY += 32;
  doc.save();
  doc.fillColor(C.muted).font('Helvetica').fontSize(11.5);
  doc.text(String(notes), MARGIN, textY, { width: innerW });
  doc.restore();
  textY = doc.y + 26;

  roundRectFilled(doc, MARGIN, textY, innerW, 22, 8, C.rowAlt, C.periodBandBorder, 1);
  doc.save();
  doc.fillColor(C.title).font('Helvetica-Bold').fontSize(13);
  doc.text('Photos', MARGIN + 12, textY + 5);
  doc.restore();
  textY += 36;

  var gapX = 12;
  var gapY = 14;
  var cellR = 10;
  var cellW = (innerW - gapX) / 2;
  var cellH = 148;
  var currentY = textY;
  var row = 0;
  var col = 0;
  for (var i = 0; i < photos.length; i++) {
    if (currentY + row * (cellH + gapY) + cellH > pageH - 46) {
      doc.addPage();
      currentY = 72;
      row = 0;
      col = 0;
    }
    var xCell = MARGIN + col * (cellW + gapX);
    var yCell = currentY + row * (cellH + gapY);
    var buf = resolveImageToBuffer(photos[i]);
    drawPhotoCell(doc, buf, xCell, yCell, cellW, cellH, cellR);
    col += 1;
    if (col > 1) {
      col = 0;
      row += 1;
    }
  }

  foot();
}

/**
 * Invoice-style one-pager for work log email attachment (matches Time Sheet / Work Report visual language).
 * @param {import('pdfkit').PDFDocument} doc
 * @param {{
 *   companyName: string,
 *   workerName: string,
 *   workerEmail?: string,
 *   jobDisplayId: string,
 *   projectName: string,
 *   workType: string,
 *   totalStr: string,
 *   description: string,
 *   detailLines: string[],
 *   priceWorkTables?: { jobHeading: string, jobTotalStr?: string | null, rows: { stepNr: string, jobDetails: string, quantity: string, amountStr: string }[] }[],
 *   photoGroups?: { label: string, urls: string[] }[],
 *   issuedAt?: Date,
 * }} opts
 */
function renderWorkLogInvoice(doc, opts) {
  var companyName = escapeText(opts.companyName || '—');
  var workerName = escapeText(opts.workerName || 'Operative');
  var workerEmail = escapeText(opts.workerEmail || '');
  var jobDisplayId = escapeText(opts.jobDisplayId || '—');
  var projectName = escapeText(opts.projectName || '—');
  var workType = escapeText(opts.workType || '—');
  var totalStr = escapeText(opts.totalStr || '—');
  var description = opts.description != null && String(opts.description).trim() !== '' ? String(opts.description) : '—';
  var detailLines = Array.isArray(opts.detailLines) ? opts.detailLines.map(function (l) { return escapeText(l); }) : [];
  var priceWorkTables = Array.isArray(opts.priceWorkTables) ? opts.priceWorkTables : [];
  var photoGroups = Array.isArray(opts.photoGroups) ? opts.photoGroups : [];
  var issued = opts.issuedAt instanceof Date ? opts.issuedAt : new Date();
  var issuedStr = formatOneDateToDMYY(issued.toISOString().slice(0, 10));

  var sz = pageSize(doc);
  var pageW = sz.pageW;
  var pageH = sz.pageH;
  var foot = attachFooters(doc);
  doc.addPage();

  doc.save();
  doc.rect(0, 0, pageW, HEADER_BAND_H).fill(C.headerBg);
  doc.restore();

  doc.save();
  doc.fillColor(C.onHeader).font('Helvetica-Bold').fontSize(28);
  doc.text('Invoice summary', MARGIN, 36, { width: pageW - MARGIN * 2 });
  doc.fillColor(C.headerSub).font('Helvetica').fontSize(12);
  doc.text('Work log · operative submission', MARGIN, 74);
  doc.restore();

  var y0 = HEADER_BAND_H + 22;
  var bandH = 44;
  roundRectFilled(doc, MARGIN, y0, pageW - MARGIN * 2, bandH, 10, C.periodBand, C.periodBandBorder, 1);
  doc.save();
  doc.fillColor(C.title).font('Helvetica-Bold').fontSize(13);
  doc.text('Date issued:', MARGIN + 16, y0 + 14);
  doc.font('Helvetica-Bold').fontSize(14).fillColor('#1e40af');
  doc.text(issuedStr, MARGIN + 198, y0 + 13, { width: pageW - MARGIN * 2 - 220 });
  doc.restore();

  var tableTop = y0 + bandH + 18;
  var tableW = pageW - MARGIN * 2;
  var operativeVal = workerName + (workerEmail ? ' · ' + workerEmail : '');
  var tableBot = drawSummaryGrid(doc, MARGIN, tableTop, tableW, [
    { label: 'Bill to (company)', value: companyName },
    { label: 'Operative', value: operativeVal },
    { label: 'Reference', value: jobDisplayId },
    { label: 'Project', value: projectName },
    { label: 'Work type', value: workType },
    { label: 'Amount', value: totalStr },
  ]);

  var textY = tableBot + 22;
  var innerW = tableW;

  roundRectFilled(doc, MARGIN, textY, innerW, 22, 8, C.rowAlt, C.periodBandBorder, 1);
  doc.save();
  doc.fillColor(C.title).font('Helvetica-Bold').fontSize(13);
  doc.text('Description', MARGIN + 12, textY + 5);
  doc.restore();
  textY += 32;
  doc.save();
  doc.fillColor(C.title).font('Helvetica').fontSize(11.5);
  doc.text(description, MARGIN, textY, { width: innerW });
  doc.restore();
  textY = doc.y + 18;

  if (priceWorkTables.length) {
    textY = drawPriceWorkTablesBlock(doc, textY, pageW, pageH, innerW, priceWorkTables);
  } else if (detailLines.length) {
    roundRectFilled(doc, MARGIN, textY, innerW, 22, 8, C.rowAlt, C.periodBandBorder, 1);
    doc.save();
    doc.fillColor(C.title).font('Helvetica-Bold').fontSize(13);
    doc.text('QA price work / booking lines', MARGIN + 12, textY + 5);
    doc.restore();
    textY += 32;
    doc.save();
    doc.fillColor(C.muted).font('Helvetica').fontSize(10);
    doc.text(detailLines.join('\n'), MARGIN, textY, { width: innerW });
    doc.restore();
    textY = doc.y + 18;
  }

  if (photoGroups.length) {
    if (textY + 36 > pageH - 56) {
      doc.addPage();
      textY = 56;
    }
    roundRectFilled(doc, MARGIN, textY, innerW, 22, 8, C.rowAlt, C.periodBandBorder, 1);
    doc.save();
    doc.fillColor(C.title).font('Helvetica-Bold').fontSize(13);
    doc.text('Photo confirmation', MARGIN + 12, textY + 5);
    doc.restore();
    var cursorY = textY + 32;
    var photoRowH = 118;
    photoGroups.forEach(function (g) {
      var urls = Array.isArray(g.urls) ? g.urls.filter(function (u) { return u && String(u).trim(); }) : [];
      if (!urls.length) return;
      var gLabel = escapeText(g.label || 'Step');
      if (cursorY + 28 > pageH - 56) {
        doc.addPage();
        cursorY = 56;
      }
      doc.save();
      doc.fillColor(C.title).font('Helvetica-Bold').fontSize(10.5);
      doc.text(gLabel, MARGIN, cursorY, { width: innerW });
      doc.restore();
      cursorY = doc.y + 6;
      urls.forEach(function (url) {
        if (cursorY + photoRowH > pageH - 56) {
          doc.addPage();
          cursorY = 56;
        }
        var buf = resolveImageToBuffer(url);
        drawPhotoCell(doc, buf, MARGIN, cursorY, innerW, photoRowH, 10);
        cursorY += photoRowH + 8;
      });
      cursorY += 4;
    });
    textY = cursorY;
  }

  var discText =
    'Pending manager review in Work Logs. Not a final tax invoice unless confirmed by your company.';
  doc.font('Helvetica').fontSize(10);
  var discBoxH = doc.heightOfString(discText, { width: innerW - 24 }) + 20;
  if (textY + discBoxH + 30 > pageH - 40) {
    doc.addPage();
    textY = 56;
  }
  roundRectFilled(doc, MARGIN, textY, innerW, Math.max(36, discBoxH), 8, '#fef3c7', '#fbbf24', 1);
  doc.save();
  doc.fillColor('#92400e').font('Helvetica').fontSize(10);
  doc.text(discText, MARGIN + 12, textY + 10, { width: innerW - 24 });
  doc.restore();

  foot();
}

module.exports = {
  formatDateRange,
  resolveImageToBuffer,
  renderTimesheet,
  renderWorkReport,
  renderWorkLogInvoice,
};
